In [1]:
!pip install evaluate
!pip install rouge_score

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (1.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from evaluate) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (4.0.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (23.0.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2026.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.25.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.8 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from rouge_score) (2.1.3)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk->rouge_score) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk->rouge_score) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk->rouge_score) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk->rouge_score) (3.1.2)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24986 sha256=32c12e390f8a0624a5b81ce84c869b95ae03d1caa1b74f118502038d71eded51
  Stored in directory: /root/.cache/pip/wheels/44/af/da/5ffc433e2786f0b1a9c6f458d5fb8f611d8eb332387f18698f
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [2]:
from datasets import load_dataset
import textwrap
import pandas as pd
import numpy as np
import plotly.express as px
from datasets import Dataset
import evaluate
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments
from transformers import DataCollatorForSeq2Seq

In [3]:
data_set = load_dataset("abisee/cnn_dailymail", name="3.0.0")
df = pd.DataFrame(data_set['train'][:10000])
print("Done and the Shape is:", df.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

3.0.0/train-00000-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00000-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00001-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00001-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00002-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  259MB

3.0.0/train-00002-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 34.7MB

3.0.0/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

3.0.0/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 30.0MB

3.0.0/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

Done and the Shape is: (10000, 3)

In [4]:
df

,article,highlights,id
0,"LONDON, England (Reuters) -- Harry Potter star...",Harry Potter star Daniel Radcliffe gets £20M f...,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
1,Editor's note: In our Behind the Scenes series...,Mentally ill inmates in Miami are housed on th...,ee8871b15c50d0db17b0179a6d2beab35065f1e9
2,"MINNEAPOLIS, Minnesota (CNN) -- Drivers who we...","NEW: ""I thought I was going to die,"" driver sa...",06352019a19ae31e527f37f7571c6dd7f0c5da37
3,WASHINGTON (CNN) -- Doctors removed five small...,"Five small polyps found during procedure; ""non...",24521a2abb2e1f5e34e6824e0f9e56904a2b0e88
4,(CNN) -- The National Football League has ind...,"NEW: NFL chief, Atlanta Falcons owner critical...",7fe70cc8b12fab2d0a258fababf7d9c6b5e1262a
...,...,...,...
9995,"(Oprah.com) -- As a trained chef, restaurant o...",Chef Laura Pensiero: Don't let diet hijack you...,75cd2144a44f902e14b887bf927a08ad6b5fbf54
9996,"Islamabad, Pakistan (CNN) -- The Pakistani mil...",NEW: Taliban source says commander alive and w...,734ca9a754dd444ed50362375e256fd72d82def5
9997,(CNN) -- Bastian Schweinsteiger rescued a poin...,Midfielder Bastian Schweinsteiger rescues a po...,8ff4e932c84ed30759427a128879f0af1c8a156a
9998,"(CNN) -- Haiti's earthquake is creating ""a gen...","Experts say Haiti's earthquake is creating ""a ...",12e6c95b6f47092e953523ae556cb6391a7021f6
9999,(SuperYachtWorld) -- They may not be big on lo...,New breed of adventure explorers offer comfort...,1130b36a9ba93d8fcbf07a2ac0048d4c281cd57c

In [5]:
print("Article:\n")
print(textwrap.fill(df['article'].iloc[0]))
print("\n" + "="*100 + "\n")
print("Highlights:\n")
print(df['highlights'].iloc[0])

Article:

LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains
access to a reported £20 million ($41.1 million) fortune as he turns
18 on Monday, but he insists the money won't cast a spell on him.
Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the
Phoenix" To the disappointment of gossip columnists around the world,
the young actor says he has no plans to fritter his cash away on fast
cars, drink and celebrity parties. "I don't plan to be one of those
people who, as soon as they turn 18, suddenly buy themselves a massive
sports car collection or something similar," he told an Australian
interviewer earlier this month. "I don't think I'll be particularly
extravagant. "The things I like buying are things that cost about 10
pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to
gamble in a casino, buy a drink in a pub or see the horror film
"Hostel: Part II," currently six places below his number one movie on
the UK box office chart. Details of how he'll mark his landmark
birthday are under wraps. His agent and publicist had no comment on
his plans. "I'll definitely have some sort of party," he said in an
interview. "Hopefully none of you will be reading about it."
Radcliffe's earnings from the first five Potter films have been held
in a trust fund which he has not been able to touch. Despite his
growing fame and riches, the actor says he is keeping his feet firmly
on the ground. "People are always looking to say 'kid star goes off
the rails,'" he told reporters last month. "But I try very hard not to
go that way because it would be too easy for them." His latest outing
as the boy wizard in "Harry Potter and the Order of the Phoenix" is
breaking records on both sides of the Atlantic and he will reprise the
role in the last two films.  Watch I-Reporter give her review of
Potter's latest » . There is life beyond Potter, however. The Londoner
has filmed a TV movie called "My Boy Jack," about author Rudyard
Kipling and his son, due for release later this year. He will also
appear in "December Boys," an Australian film about four boys who
escape an orphanage. Earlier this year, he made his stage debut
playing a tortured teenager in Peter Shaffer's "Equus." Meanwhile, he
is braced for even closer media scrutiny now that he's legally an
adult: "I just think I'm going to be more sort of fair game," he told
Reuters. E-mail to a friend . Copyright 2007 Reuters. All rights
reserved.This material may not be published, broadcast, rewritten, or
redistributed.

====================================================================================================

Highlights:

Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .
Young actor says he has no plans to fritter his cash away .
Radcliffe's earnings from first five Potter films have been held in trust fund .

In [6]:
df.drop(columns=['id'],inplace=True)

In [7]:
print(df.info())
print("\n" + "="*100)

print(f'the duplicate is: ' ,df.duplicated().sum())
print("\n" + "="*100)

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   article     10000 non-null  object
 1   highlights  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB
None

====================================================================================================
the duplicate is:  867

====================================================================================================

article       0
highlights    0
dtype: int64

In [8]:
df = df.drop_duplicates(subset=['article']).reset_index(drop=True)
df

,article,highlights
0,"LONDON, England (Reuters) -- Harry Potter star...",Harry Potter star Daniel Radcliffe gets £20M f...
1,Editor's note: In our Behind the Scenes series...,Mentally ill inmates in Miami are housed on th...
2,"MINNEAPOLIS, Minnesota (CNN) -- Drivers who we...","NEW: ""I thought I was going to die,"" driver sa..."
3,WASHINGTON (CNN) -- Doctors removed five small...,"Five small polyps found during procedure; ""non..."
4,(CNN) -- The National Football League has ind...,"NEW: NFL chief, Atlanta Falcons owner critical..."
...,...,...
9127,"(Oprah.com) -- As a trained chef, restaurant o...",Chef Laura Pensiero: Don't let diet hijack you...
9128,"Islamabad, Pakistan (CNN) -- The Pakistani mil...",NEW: Taliban source says commander alive and w...
9129,(CNN) -- Bastian Schweinsteiger rescued a poin...,Midfielder Bastian Schweinsteiger rescues a po...
9130,"(CNN) -- Haiti's earthquake is creating ""a gen...","Experts say Haiti's earthquake is creating ""a ..."
9131,(SuperYachtWorld) -- They may not be big on lo...,New breed of adventure explorers offer comfort...

In [9]:
print(f'The Dublicated is :',df.duplicated().sum())

The Dublicated is : 0

In [10]:
df.describe()

,article,highlights
count,9132,9132
unique,9132,9088
top,(SuperYachtWorld) -- They may not be big on lo...,Rick Steves writes European travel guidebooks ...
freq,1,5

In [11]:
df['article_length'] = df['article'].apply(lambda x: len(x.split()))
df['highlights_length'] = df['highlights'].apply(lambda x: len(x.split()))

display(df[['article_length','highlights_length']].describe())

       article_length  highlights_length
count     9132.000000        9132.000000
mean       623.026500          44.711345
std        309.013442           8.084830
min         18.000000          11.000000
25%        376.000000          38.000000
50%        579.000000          45.000000
75%        829.000000          51.000000
max       1831.000000          85.000000

In [12]:
px.histogram(df, x='article_length',
             nbins=30,
             title = 'Distribution of Article Length',
             color_discrete_sequence=['blue'])

In [13]:
px.box(df,
       y = ['article_length','highlights_length'],
       title = 'Box Plot for Article_length Highlights_length',
       color_discrete_sequence=['pink'],
       )

In [14]:
fig_violin = px.violin(df,
                       y = ['article_length', 'highlights_length'],
                       title = 'Violin Plot',
                       box = True,
                       points = 'outliers',
                       color_discrete_sequence = ['Violet'])
fig_violin.show()

In [15]:
px.density_heatmap(df,
                   x = 'article_length',
                   y = 'highlights_length',
                   title = 'Heatmap of Article Length vs. Highlights Length',
                   color_continuous_scale='plasma')

In [16]:
df_clean = df[
    (df['article_length'] >= 100) & (df['article_length'] <= 1000) &
    (df['highlights_length'] >= 10) & (df['highlights_length'] <= 100)
    ].copy().reset_index(drop=True)
df_clean

,article,highlights,article_length,highlights_length
0,"LONDON, England (Reuters) -- Harry Potter star...",Harry Potter star Daniel Radcliffe gets £20M f...,455,41
1,Editor's note: In our Behind the Scenes series...,Mentally ill inmates in Miami are housed on th...,698,49
2,"MINNEAPOLIS, Minnesota (CNN) -- Drivers who we...","NEW: ""I thought I was going to die,"" driver sa...",743,43
3,WASHINGTON (CNN) -- Doctors removed five small...,"Five small polyps found during procedure; ""non...",414,27
4,(CNN) -- The National Football League has ind...,"NEW: NFL chief, Atlanta Falcons owner critical...",973,44
...,...,...,...,...
7952,Spin bowlers Harbhajan Singh and Murali Kartik...,India have recalled Harbhajan Singh and Murali...,324,42
7953,(CNN) -- Self-help guru James Ray was arrested...,Self-help guru James Ray was arrested Wednesda...,309,56
7954,(OPRAH.com) -- Allow me to introduce myself. I...,Columnist Lisa Kogan says please don't say the...,943,56
7955,"Islamabad, Pakistan (CNN) -- The Pakistani mil...",NEW: Taliban source says commander alive and w...,224,49
7956,(CNN) -- Bastian Schweinsteiger rescued a poin...,Midfielder Bastian Schweinsteiger rescues a po...,386,63

In [17]:
df_train, df_test = train_test_split(df_clean, test_size = 0.2, random_state = 42)

print("train size (Train):", df_train.shape)
print("test size (Test):", df_test.shape)

train size (Train): (6365, 4)
test size (Test): (1592, 4)

In [18]:
model = AutoModelForSeq2SeqLM.from_pretrained('facebook/bart-large-cnn')
tokenizer = AutoTokenizer.from_pretrained('facebook/bart-large-cnn')

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [19]:
train_dataset = Dataset.from_pandas(df_train)
test_dataset = Dataset.from_pandas(df_test)

def preprocess_function(examples):
    model_inputs = tokenizer(examples['article'],
                             max_length = 1024,
                             truncation = True,
                             padding = 'max_length')

    labels = tokenizer(examples['highlights'],
                       max_length = 128,
                       padding = 'max_length',
                       truncation = True)

    model_inputs['labels'] = labels['input_ids']
    return model_inputs

tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

Map:   0%|          | 0/6365 [00:00<?, ? examples/s]

Map:   0%|          | 0/1592 [00:00<?, ? examples/s]

In [20]:
rouge_metric = evaluate.load('rouge')

def compute_metrics(eval_pred):
  predictions, labels = eval_pred
  decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)

  labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
  decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

  result = rouge_metric.compute(predictions = decoded_preds, references = decoded_labels, use_stemmer = True)
  return {k: round(v * 100, 4) for k, v in result.items()}


training_args = Seq2SeqTrainingArguments(
    output_dir = "./bart_summarization_results",
    eval_strategy = "epoch",
    learning_rate = 2e-5,
    num_train_epochs = 1,
    weight_decay = 0.01,
    per_device_train_batch_size = 4,
    per_device_eval_batch_size = 4,
    predict_with_generate = True,
    )

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model = model,
    args = training_args,
    train_dataset = tokenized_train,
    eval_dataset = tokenized_test,
    data_collator = data_collator,
    compute_metrics = compute_metrics,
    )

trainer.train()

Downloading builder script: 0.00B [00:00, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1592, training_loss=0.62100848959918, metrics={'train_runtime': 6348.5739, 'train_samples_per_second': 1.003, 'train_steps_per_second': 0.251, 'total_flos': 1.379362079244288e+16, 'train_loss': 0.62100848959918, 'epoch': 1.0})

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [23]:
save_path = "/content/drive/MyDrive/my_saved_bart_model"

trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('/content/drive/MyDrive/my_saved_bart_model/tokenizer_config.json',
 '/content/drive/MyDrive/my_saved_bart_model/tokenizer.json')